Repository prgrms-web-devcourse-final-project/WEB6_8_OneTop_BE, pull requests merged in 2025-09, with the labels that each got.

#10 [REFACTOR]: Scenario Entity 분석 및 보완
  .gitignore
  back/.gitignore
  back/src/main/java/com/back/domain/scenario/entity/Scenario.java
  back/src/main/java/com/back/domain/scenario/entity/ScenarioRequest.java
  back/src/main/java/com/back/domain/scenario/entity/ScenarioStatus.java
  back/src/main/java/com/back/domain/scenario/repository/ScenarioRequestRepository.java
  back/src/main/java/com/back/domain/scenario/service/ScenarioService.java
Labels: REFACTOR

#16 [FEAT]: 시나리오 Controller & DTO 작성
  .gitignore
  back/src/main/java/com/back/domain/scenario/controller/ScenarioController.java
  back/src/main/java/com/back/domain/scenario/dto/BaselineListResponse.java
  back/src/main/java/com/back/domain/scenario/dto/ScenarioCompareResponse.java
  back/src/main/java/com/back/domain/scenario/dto/ScenarioCreateRequest.java
  back/src/main/java/com/back/domain/scenario/dto/ScenarioDetailResponse.java
  back/src/main/java/com/back/domain/scenario/dto/ScenarioStatusResponse.java
  back/src/main/java/com/back/domain/scenario/dto/ScenarioTypeDto.java
  back/src/main/java/com/back/domain/scenario/dto/TimelineResponse.java
  back/src/main/java/com/back/domain/scenario/entity/Scenario.java
Labels: FEAT

#20 [FEAT]: 시나리오 Service Layer 구현
  .gitignore
  back/src/main/java/com/back/domain/scenario/controller/ScenarioController.java
  back/src/main/java/com/back/domain/scenario/dto/BaselineListResponse.java
  back/src/main/java/com/back/domain/scenario/dto/ScenarioCompareResponse.java
  back/src/main/java/com/back/domain/scenario/dto/TimelineResponse.java
  back/src/main/java/com/back/domain/scenario/entity/Scenario.java
  back/src/main/java/com/back/domain/scenario/entity/SceneCompare.java
  back/src/main/java/com/back/domain/scenario/repository/ScenarioRepository.java
  back/src/main/java/com/back/domain/scenario/repository/SceneCompareRepository.java
  back/src/main/java/com/back/domain/scenario/repository/SceneTypeRepository.java
  back/src/main/java/com/back/domain/scenario/service/ScenarioService.java
  back/src/main/java/com/back/global/config/JsonConfig.java
  back/src/main/java/com/back/global/exception/ErrorCode.java
Labels: FEAT

#22 [FEAT]: 시나리오 테스트 코드 작성
  back/src/main/java/com/back/domain/scenario/controller/ScenarioController.java
  back/src/test/java/com/back/domain/scenario/controller/ScenarioControllerTest.java
  back/src/test/java/com/back/domain/scenario/service/ScenarioServiceTest.java
  back/src/test/java/com/back/global/config/JsonConfigTest.java
Labels: FEAT

#24 [FEAT]: 결정노드 생성 및 저장 & ProblemDetail 사용
  back/src/main/java/com/back/domain/node/controller/BaseLineController.java
  back/src/main/java/com/back/domain/node/controller/DecisionFlowController.java
  back/src/main/java/com/back/domain/node/controller/DecisionFromBaseController.java
  back/src/main/java/com/back/domain/node/dto/BaseLineBulkCreateRequest.java
  back/src/main/java/com/back/domain/node/dto/BaseLineDto.java
  back/src/main/java/com/back/domain/node/dto/BaseNodeDto.java
  back/src/main/java/com/back/domain/node/dto/DecLineDto.java
  back/src/main/java/com/back/domain/node/dto/DecisionNodeCreateRequestDto.java
  back/src/main/java/com/back/domain/node/dto/DecisionNodeFromBaseRequest.java
  back/src/main/java/com/back/domain/node/dto/DecisionNodeNextRequest.java
  back/src/main/java/com/back/domain/node/dto/TreeDto.java
  back/src/main/java/com/back/domain/node/entity/BaseLine.java
  back/src/main/java/com/back/domain/node/entity/BaseNode.java
  back/src/main/java/com/back/domain/node/entity/DecisionNode.java
  back/src/main/java/com/back/domain/node/mapper/NodeMappers.java
  back/src/main/java/com/back/domain/node/repository/BaseLineRepository.java
  back/src/main/java/com/back/domain/node/service/BaseLineService.java
  back/src/main/java/com/back/domain/node/service/DecisionFlowService.java
  back/src/main/java/com/back/domain/node/service/NodeDomainSupport.java
  back/src/main/java/com/back/domain/node/service/NodeQueryService.java
  back/src/main/java/com/back/domain/node/service/NodeService.java
  back/src/main/java/com/back/global/config/JsonConfig.java
  back/src/main/java/com/back/global/exception/GlobalExceptionHandler.java
  back/src/main/java/com/back/global/jackson/ProblemDetailJsonSerializer.java
  back/src/main/java/com/back/global/problemdetail/ProblemDetails.java
  back/src/test/java/com/back/domain/node/controller/BaseLineControllerTest.java
  back/src/test/java/com/back/domain/node/controller/DecisionFlowControllerTest.java
Labels: FEAT

#30 [FEAT]: 결정라인 및 트리구조 조회 구현
  back/src/main/java/com/back/domain/node/controller/BaseLineController.java
  back/src/main/java/com/back/domain/node/controller/DecisionLineController.java
  back/src/main/java/com/back/domain/node/dto/DecisionLineDetailDto.java
  back/src/main/java/com/back/domain/node/dto/DecisionLineListDto.java
  back/src/main/java/com/back/domain/node/dto/TreeDto.java
  back/src/main/java/com/back/domain/node/repository/DecisionLineRepository.java
  back/src/main/java/com/back/domain/node/repository/DecisionNodeRepository.java
  back/src/main/java/com/back/domain/node/service/DecisionFlowService.java
  back/src/main/java/com/back/domain/node/service/NodeDomainSupport.java
  back/src/main/java/com/back/domain/node/service/NodeQueryService.java
  back/src/main/java/com/back/domain/node/service/NodeService.java
  back/src/test/java/com/back/domain/node/controller/BaseLineControllerTest.java
  back/src/test/java/com/back/domain/node/controller/DecisionLineControllerTest.java
Labels: FEAT

#38 [REFACTOR]: 소유자 검증 & 분기점에서 새로운 결정 분기 라인 생성 & 헤더 추가
  back/src/main/java/com/back/domain/node/controller/BaseLineController.java
  back/src/main/java/com/back/domain/node/controller/DecisionFlowController.java
  back/src/main/java/com/back/domain/node/controller/DecisionLineController.java
  back/src/main/java/com/back/domain/node/dto/PivotListDto.java
  back/src/main/java/com/back/domain/node/dto/TreeDto.java
  back/src/main/java/com/back/domain/node/dto/base/BaseLineBulkCreateRequest.java
  back/src/main/java/com/back/domain/node/dto/base/BaseLineBulkCreateResponse.java
  back/src/main/java/com/back/domain/node/dto/base/BaseNodeCreateRequestDto.java
  back/src/main/java/com/back/domain/node/dto/base/BaseNodeDto.java
  back/src/main/java/com/back/domain/node/dto/decision/DecNodeDto.java
  back/src/main/java/com/back/domain/node/dto/decision/DecisionLineDetailDto.java
  back/src/main/java/com/back/domain/node/dto/decision/DecisionLineLifecycleDto.java
  back/src/main/java/com/back/domain/node/dto/decision/DecisionLineListDto.java
  back/src/main/java/com/back/domain/node/dto/decision/DecisionNodeCreateRequestDto.java
  back/src/main/java/com/back/domain/node/dto/decision/DecisionNodeFromBaseRequest.java
  back/src/main/java/com/back/domain/node/dto/decision/DecisionNodeNextRequest.java
  back/src/main/java/com/back/domain/node/dto/decision/ForkFromDecisionRequest.java
  back/src/main/java/com/back/domain/node/entity/BaseNode.java
  back/src/main/java/com/back/domain/node/entity/DecisionNode.java
  back/src/main/java/com/back/domain/node/mapper/NodeMappers.java
  back/src/main/java/com/back/domain/node/repository/BaseNodeRepository.java
  back/src/main/java/com/back/domain/node/repository/DecisionNodeRepository.java
  back/src/main/java/com/back/domain/node/service/BaseLineService.java
  back/src/main/java/com/back/domain/node/service/DecisionFlowService.java
  back/src/main/java/com/back/domain/node/service/NodeDomainSupport.java
  back/src/main/java/com/back/domain/node/service/NodeQueryService.java
  back/src/main/java/com/back/domain/node/service/NodeService.java
  back/src/test/java/com/back/domain/node/controller/BaseLineControllerTest.java
  back/src/test/java/com/back/domain/node/controller/DecisionFlowControllerTest.java
Labels: REFACTOR

#42 [CHORE]: initdata 수정
  back/src/main/java/com/back/domain/comment/service/CommentService.java
  back/src/main/java/com/back/domain/node/controller/BaseLineController.java
  back/src/main/java/com/back/domain/node/repository/BaseLineRepository.java
  back/src/main/java/com/back/domain/node/service/BaseLineService.java
  back/src/main/java/com/back/global/exception/ErrorCode.java
  back/src/main/java/com/back/global/initdata/InitData.java
  back/src/test/java/com/back/domain/comment/controller/CommentControllerTest.java
  back/src/test/java/com/back/domain/node/controller/BaseLineControllerTest.java
  back/src/test/java/com/back/domain/node/controller/DecisionFlowControllerTest.java
  back/src/test/java/com/back/domain/node/controller/DecisionLineControllerTest.java
  back/src/test/java/com/back/domain/post/controller/PostControllerTest.java
Labels: CHORE

#46 [FEAT]: 사용자가 가진 baseline 리스트 조회
  back/src/main/java/com/back/domain/node/controller/BaseLineController.java
  back/src/main/java/com/back/domain/node/dto/base/BaseLineDto.java
  back/src/main/java/com/back/domain/node/mapper/NodeMappers.java
  back/src/main/java/com/back/domain/node/repository/BaseLineRepository.java
  back/src/main/java/com/back/domain/node/service/NodeQueryService.java
  back/src/main/java/com/back/domain/node/service/NodeService.java
  back/src/test/java/com/back/domain/node/controller/BaseLineControllerTest.java
Labels: FEAT

#48 [FEAT]: 투표 게시글 생성 및 투표 기능 구현
  back/src/main/java/com/back/domain/comment/entity/Comment.java
  back/src/main/java/com/back/domain/poll/controller/PollVoteController.java
  back/src/main/java/com/back/domain/poll/converter/PollConverter.java
  back/src/main/java/com/back/domain/poll/dto/PollOptionResponse.java
  back/src/main/java/com/back/domain/poll/dto/PollRequest.java
  back/src/main/java/com/back/domain/poll/dto/PollResponse.java
  back/src/main/java/com/back/domain/poll/dto/VoteRequest.java
  back/src/main/java/com/back/domain/poll/entity/PollVote.java
  back/src/main/java/com/back/domain/poll/repository/PollVoteRepository.java
  back/src/main/java/com/back/domain/poll/service/PollVoteService.java
  back/src/main/java/com/back/domain/post/dto/PostDetailResponse.java
  back/src/main/java/com/back/domain/post/dto/PostRequest.java
  back/src/main/java/com/back/domain/post/entity/Post.java
  back/src/main/java/com/back/domain/post/mapper/PostMappers.java
  back/src/main/java/com/back/domain/post/service/PostService.java
  back/src/main/java/com/back/global/exception/ErrorCode.java
  back/src/main/java/com/back/global/exception/GlobalExceptionHandler.java
  back/src/main/java/com/back/global/initdata/InitData.java
  back/src/test/java/com/back/domain/poll/controller/PollVoteControllerTest.java
  back/src/test/java/com/back/domain/post/controller/PostControllerTest.java
Labels: FEAT
